### ISSUE TITLE
Disabling "Plant All Seasons" crashes the mod.

### ISSUE THREAD

**Issue by Rupurudu** [p-holodynski/StardewValleyMods#1]
https://smapi.io/log/10f83f025d554452984732539b4a010
[SMAPI-latest.txt](https://github.com/p-holodynski/StardewValleyMods/files/8598907/SMAPI-latest.txt)
0

**Comment by p-holodynski** [comment]
Hello,

thanks for reporting.

Could you tell me the conditions under which you were running ur game?

Was it Single or Multiplayer?

Was it fresh save or old save?

I see that you have a lot mods installed.

Did you use the latest version of the mod (1.2.0) when this happened?

Thanks and I will try to find the issue

**Comment by Rupurudu** [comment]
Hello, 
The error happens before loading a save. In the main menu. We are playing multiplayer, with fresh save. (just 2 days old, we are in first year.)

**Comment by p-holodynski** [comment]
Hi, could you try the updated version and let me know if the issue persist?
https://www.nexusmods.com/stardewvalley/mods/11840?tab=files&file_id=53913
Thanks

**Comment by Rupurudu** [comment]
Hello,
The issue is fixed, no more errors on main menu and singleplayer.
Thank you for the mod!
